// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cdhihqaylfgoztunvkab.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNkaGlocWF5bGZnb3p0dW52a2FiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNDYwNDMsImV4cCI6MjA2NTgyMjA0M30.DddaHYS36l6jc17-_l_JoLKJ9BoCuzVZDGgv9pb20Us";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);